export { default as Background } from './Background'
export { default as Center } from './Center'
export { default as Content } from './Content'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as Avatar } from './Avatar'
export { default as VerticalLine } from './VerticalLine'
